name: Deploy to Server

on:
  push:
    branches:
      - umair_branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: ${{ secrets.EC2_PORT }}
          script: |
            cd ~/Inbound_Calling
            git pull
            sudo docker compose down
            sudo docker compose build --no-cache
            sudo docker compose up -d

